# Generated by Django 5.2.1 on 2025-05-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Task Description')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('task_is_done', models.BooleanField(default=False, verbose_name='Task is Done')),
                ('tags', models.ManyToManyField(related_name='tasks', to='catalog.tag', verbose_name='Tags')),
            ],
        ),
    ]
