# Generated by Django 5.2.1 on 2025-05-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
